### ISSUE TITLE
Idea for structuring repo

### ISSUE THREAD

**Issue by bvssvni** [PistonDevelopers/shaders#28]
See https://github.com/PistonDevelopers/graphics/issues/875

Shaders are used in widely different contexts, so it does not make sense to make one big crate that contains all the source.

For example, there could be one crate for simple 2D shaders that are used across the 2D graphics back-ends.

**Comment by bvssvni** [comment]
Does Cargo allow multiple libraries in the same repository?

**Comment by kvark** [comment]
@bvssvni surely, I'm doing this with `claymore`, `gfx_scene`, and `simplecs`. Basically, the main lib/exe lists the sub-crates as dependencies, and these ones can be accessed by other projects using the same git path (like [here](https://github.com/kvark/claymore/blob/master/src/scene/Cargo.toml#L12))

**Comment by bvssvni** [comment]
I'll remove the viewer example and assets for now. The top crate could be named "shaders" and reexport the others, starting with a "shader_" prefix. This way you can depend on "shaders_graphics2d" directly or use `shaders::graphics2d`.

**Comment by bvssvni** [comment]
Done.
